### ISSUE TITLE
Gaze direction estimation

### ISSUE THREAD

**Issue by marcodemutti** [Rassibassi/mediapipeDemos#10]
Hello Rasmus,

thank you for your precious work. I am working on Human-Robot Interaction and I would like to extract both the head posture (yaw-pitch-roll-angles), but also to have an estimation of the gaze direction relative to the face plane (ideally, I would like to have the yaw and pitch angles, but also a rough estimate of the angle between the normals of the two planes would be fine). For the first task, your "head_posture.py" code amazingly does the job. The second one appears to be more tricky. I identified a plane parallel to the face (best fitting a few landmarks) and a plane parallel to the iris, but I realized that the assumption is that the iris plane is always parallel to the image plane, so this is not the way to do it.
Do you have any suggestions on how to do the job? Or at least, do you think it is possible starting from the code you provided?

Thank you.

Marco

**Comment by Rassibassi** [comment]
Hi,

nice! I'm happy you reached out. I got into mediapipe for the very same problem you are tackling. It is a very hard problem and still an open research topic. [Here is a good entry point to the research community](https://gazeworkshop.github.io/2022/). I'll leave you with some thoughts.

I've got a "somewhat" working prototype in Python which estimated the gaze vector and projects it against the screen estimating where the user is looking on the screen. However, after the initial calibration, the system starts drifting and accuracy suffers. I would love to push what I have all the way to a mediapipe unit to see how good it works on a tablet, but it is very time consuming and a challenge in itself.

This is the pipeline I have implemented in Python:
1. Face detection and face mesh detection using mediapipe
2. Eye patch extraction and stabilization, Kalman filter or 1 euro filter
3. Eye patch normalization with the estimated the head pose [1]
4. Normalized gaze vector estimation from eye patch as presented in this EVE publication [2]
5. De-normalization of gaze vector to user coordinate system
6. Data aided estimation of extrinsic camera parameters via calibration with the user looking at certain points on the screen [3]
7. Transformation of gaze vector from user coordinate system to screen coordinate system via extrinsic camera parameters
8. Projecting gaze vector against screen and converting to pixel values

Since the pre-processing mediapipe pipeline above  is slightly different than the one from EVE, it is probably beneficial to re-train the DNN from EVE based on re-pre-processed data (step 1-3). Fortunately, the data from EVE is available upon request, so I've also done that part.

I spent ~6 months on this problem in 2021. Let me talk to the institution I was working for, and see if we can somehow share the code under their flag. 

Let me ask you, what is your ambition with the gaze vector? Academic or professional? And what is your background?

Best,
Rasmus

[1] https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/gaze-based-human-computer-interaction/revisiting-data-normalization-for-appearance-based-gaze-estimation/
[2] https://github.com/swook/EVE and https://ait.ethz.ch/projects/2020/EVE/
[3] https://arxiv.org/abs/2009.01270, see Section 4 on Screen Calibration Methods``
